smart_core_felib:
    path: 'bundles/felib/' # тут можно переопределить дефолнтное положение библиотек.
    profile: yandex # использовать профиль, по умолчанию отключено.
    defaults:
        jquery: 2.1.0
    libs:
        tinymce: # новая библиотека
            deps: jquery
            version: 3.5.10
            js: tiny_mce.js
            path: 'assets/' # путь к библиотеки взамен дефолтного bundles/felib/, относительные пути будут дописаны после basePath.
        jquery:
            path: 'http://mystatic.server/mylibs/' # переопределение пути только для jquery.
