ace: # v1.1.3
    js: ace.js

bootstrap:
    version: 2.3.2
    deps: jquery
    css: [css/bootstrap.min.css, css/bootstrap-responsive.min.css]
    js: js/bootstrap.min.js

codemirror: # v4.0
    css: lib/codemirror.css
    js: lib/codemirror.js

highlightjs:
    version: 8.0
    css:
        - styles/github.min.css
        - styles/vs.min.css
    js:
        - highlight.min.js
        - languages/php.min.js
    profile:
        yandex:
            js: http://yandex.st/highlightjs/

jquery:
    version: 1.9.1
    proirity: 1000
    js: jquery.min.js
    profile:
        google:
            js: //ajax.googleapis.com/ajax/libs/jquery/
        yandex:
            js: http://yandex.st/jquery/

jquery-colorbox:
    deps: jquery
    version: 1.5.10
    css: example1/colorbox.css
    js: jquery.colorbox-min.js

jquery-cookie:
    deps: jquery
    version: 1.3.1
    js: jquery.cookie.js

less:
    version: 1.7.3
    js: less.min.js

modernizr:
    version: 2.7.1
    js: modernizr.min.js
    profile:
        yandex:
            js: http://yandex.st/modernizr/

syntaxhighlighter: # 3.0.83
    css:
        - styles/shCore.css
        - styles/shThemeRDark.css
    js:
        - scripts/shCore.js
        - scripts/shBrushBash.js
        - scripts/shBrushCpp.js
        - scripts/shBrushCss.js
        - scripts/shBrushIni.js
        - scripts/shBrushJScript.js
        - scripts/shBrushPhp.js
        - scripts/shBrushPlain.js
        - scripts/shBrushSql.js
        - scripts/shBrushTwig.js
        - scripts/shBrushXml.js
        - scripts/shBrushYaml.js
