ace: # v1.1.3
    js: ace.js

angular:
    version: 1.4
    js: angular.min.js
    dev:
        js: angular.js

bootstrap:
    version: 4
    version_code: 4.4.1
    deps: jquery
    css: css/bootstrap.min.css
    js: js/bootstrap.min.js
    dev:
        css: css/bootstrap.css
        js: js/bootstrap.js
    versions:
        2:
            css: [ css/bootstrap.min.css, css/bootstrap-responsive.min.css ]
            dev:
                css: [ css/bootstrap.css, css/bootstrap-responsive.css ]

bootstrap-colorpicker:
    deps: bootstrap
    css: css/bootstrap-colorpicker.min.css
    js: js/bootstrap-colorpicker.min.js
    dev:
        css: css/bootstrap-colorpicker.css
        js: js/bootstrap-colorpicker.js

bootstrap-datepicker:
    css: css/bootstrap-datepicker.min.css
    js:  js/bootstrap-datepicker.min.js
    deps: bootstrap
    dev:
        css: css/bootstrap-datepicker.css # bootstrap-datepicker.ru.min.css
        js: js/bootstrap-datepicker.js

bootstrap-daterangepicker:
    deps: [ bootstrap, moment ]
    css: daterangepicker.css
    jS: daterangepicker.js

bootstrap-slider:
    deps: bootstrap
    css: slider.css
    js: bootstrap-slider.js

bootstrap-timepicker:
    deps: bootstrap
    css: css/timepicker.less
    js: js/bootstrap-timepicker.js

codemirror:
    version_code: 5.19.0
    css: lib/codemirror.css
    js: lib/codemirror.js

eve-raphael:
    js: eve.js

fastclick:
    js: fastclick.js

font-awesome:
    version: 4
    version_code: 4.7.0
    css: css/font-awesome.min.css
    dev:
        css: css/font-awesome.css
    profile:
        bootstrapcdn:
            css: //maxcdn.bootstrapcdn.com/font-awesome/

iefix:
    js: [ html5shiv.min.js, respond.min.js ]

ionicons:
    version: 2.0.1
    css: css/ionicons.min.css
    dev:
        css: css/ionicons.css
    profile:
        ionicframework:
            css: //code.ionicframework.com/ionicons/

#highlightjs: @todo
#    version: 8.0
#    css:
#        - styles/github.min.css
#        - styles/vs.min.css
#    js:
#        - highlight.min.js
#        - languages/php.min.js
#    profile:
#        yandex:
#            js: http://yandex.st/highlightjs/

jcarousel:
    deps: [jquery, modernizr]
    css: jquery.jcarousel.css
    js: jquery.jcarousel.min.js

jquery:
    version: 3.2.1
    proirity: 1000
    js: jquery.min.js
    dev:
        js: jquery.js
    profile:
        google:
            js: //ajax.googleapis.com/ajax/libs/jquery/
        yandex:
            js: http://yandex.st/jquery/

jquery-colorbox:
    deps: jquery
    version: 1.5.10
    css: example1/colorbox.css
    js: jquery.colorbox-min.js
    dev:
        js: jquery.colorbox.js

jquery-cookie:
    deps: jquery
    version: 1.3.1
    js: jquery.cookie.js

jquery-knob:
    deps: jquery
    version_code: 1.2.12
    js: jquery.knob.min.js

jquery-slimscroll:
    deps: jquery
    version_code: 1.3.8
    js: jquery.slimscroll.min.js

# https://github.com/kswedberg/jquery-smooth-scroll
jquery-smooth-scroll:
    deps: jquery
    js: jquery.smooth-scroll.js

jquery-sparkline:
    deps: jquery
    version_code: 2.1.3
    js: jquery.sparkline.min.js

jquery-ui:
    deps: jquery
    version_code: 1.11.4
    js: jquery-ui.min.js

jvectormap:
    deps: jquery
    css: jquery-jvectormap.css
    js: jquery-jvectormap.js

less:
    version: 2.5.1
    js: less.min.js

modernizr:
    version: 2.8.3
    js: modernizr.min.js
    profile:
        yandex:
            js: http://yandex.st/modernizr/

moment:
    version_code: 2.19.3
    js: moment.js
    dev:
        js: moment.min.js

morris.js:
    css: morris.css
    js: morris.min.js

nivo-slider:
    deps: jquery
    js: jquery.nivo.slider.pack.js
    css:
        - nivo-slider.css
        - themes/default/default.css

pnotify:
    deps: jquery
    css: pnotify.custom.min.css
    js: pnotify.custom.min.js

raphael:
    deps: eve-raphael
    js: raphael.min.js

select2:
    version: 4
    css: css/select2.min.css
    js: js/select2.full.min.js
    dev:
        css: css/select2.css
        js: [ js/select2.full.js, js/i18n/ru.js ]
    versions:
        3:
            css: [ select2.css, select2-bootstrap.css ]
            js: [ select2.min.js, select2_locale_ru.js ]
            dev:
                js: [ select2.js, select2_locale_ru.js ]

syntaxhighlighter: # 3.0.83
    css:
        - styles/shCore.css
        - styles/shThemeRDark.css
    js:
        - scripts/shCore.js
        - scripts/shBrushBash.js
        - scripts/shBrushCpp.js
        - scripts/shBrushCss.js
        - scripts/shBrushIni.js
        - scripts/shBrushJScript.js
        - scripts/shBrushPhp.js
        - scripts/shBrushPlain.js
        - scripts/shBrushSql.js
        - scripts/shBrushTwig.js
        - scripts/shBrushXml.js
        - scripts/shBrushYaml.js

tinymce:
    version: 4
    version_code: 4.7.3
    deps: jquery
    js: jquery.tinymce.min.js

#uploadify: # @todo
