ace: # v1.1.3
    js: ace.js

angular:
    version: 1.4
    js: angular.min.js
    dev:
        js: angular.js

bootstrap:
    version: 3
    version_code: 3.3.7
    deps: jquery
    css: css/bootstrap.min.css
    js: js/bootstrap.min.js
    dev:
        css: css/bootstrap.css
        js: js/bootstrap.js
    versions:
        2:
            css: [css/bootstrap.min.css, css/bootstrap-responsive.min.css]
            dev:
                css: [css/bootstrap.css, css/bootstrap-responsive.css]

codemirror: # v4.0
    css: lib/codemirror.css
    js: lib/codemirror.js

font-awesome:
    version: 4
    version_code: 4.4.0
    css: css/font-awesome.min.css
    dev:
        css: css/font-awesome.css
    profile:
        bootstrapcdn:
            css: //maxcdn.bootstrapcdn.com/font-awesome/

ionicons:
    version: 2.0.1
    css: css/ionicons.min.css
    dev:
        css: css/ionicons.css
    profile:
        ionicframework:
            css: //code.ionicframework.com/ionicons/

#highlightjs: @todo
#    version: 8.0
#    css:
#        - styles/github.min.css
#        - styles/vs.min.css
#    js:
#        - highlight.min.js
#        - languages/php.min.js
#    profile:
#        yandex:
#            js: http://yandex.st/highlightjs/

jcarousel:
    deps: [jquery, modernizr]
    css: jquery.jcarousel.css
    js: jquery.jcarousel.min.js

jquery:
    version: 2.1.4
    proirity: 1000
    js: jquery.min.js
    dev:
        js: jquery.js
    profile:
        google:
            js: //ajax.googleapis.com/ajax/libs/jquery/
        yandex:
            js: http://yandex.st/jquery/

jquery-colorbox:
    deps: jquery
    version: 1.5.10
    css: example1/colorbox.css
    js: jquery.colorbox-min.js
    dev:
        js: jquery.colorbox.js

jquery-cookie:
    deps: jquery
    version: 1.3.1
    js: jquery.cookie.js

# https://github.com/kswedberg/jquery-smooth-scroll
jquery-smooth-scroll:
    deps: jquery
    js: jquery.smooth-scroll.js

less:
    version: 2.5.1
    js: less.min.js

modernizr:
    version: 2.8.3
    js: modernizr.min.js
    profile:
        yandex:
            js: http://yandex.st/modernizr/

nivo-slider:
    deps: jquery
    js: jquery.nivo.slider.pack.js
    css:
        - nivo-slider.css
        - themes/default/default.css
select2:
    version: 4
    css: css/select2.min.css
    js: js/select2.full.min.js
    dev:
        css: css/select2.css
        js: [ js/select2.full.js, js/i18n/ru.js ]
    versions:
        3:
            css: [ select2.css, select2-bootstrap.css ]
            js: [ select2.min.js, select2_locale_ru.js ]
            dev:
                js: [ select2.js, select2_locale_ru.js ]

syntaxhighlighter: # 3.0.83
    css:
        - styles/shCore.css
        - styles/shThemeRDark.css
    js:
        - scripts/shCore.js
        - scripts/shBrushBash.js
        - scripts/shBrushCpp.js
        - scripts/shBrushCss.js
        - scripts/shBrushIni.js
        - scripts/shBrushJScript.js
        - scripts/shBrushPhp.js
        - scripts/shBrushPlain.js
        - scripts/shBrushSql.js
        - scripts/shBrushTwig.js
        - scripts/shBrushXml.js
        - scripts/shBrushYaml.js

tinymce:
    version: 4
    version_code: 4.4.3
    deps: jquery
    js: jquery.tinymce.min.js

#uploadify: # @todo
