parameters:
#    smart_core_felib.example.class: SmartCore\Bundle\FelibBundle\Example

services:
    smart.felib:
        class: SmartCore\Bundle\FelibBundle\Service\FelibService
        arguments: [ %kernel.cache_dir%, @request_stack, @tagcache ]

    smart.felib.twig.extension:
        class: SmartCore\Bundle\FelibBundle\Twig\FelibExtension
        arguments: [ @smart.felib ]
        tags:
            - { name: twig.extension }
