services:
    smart.felib:
        class: SmartCore\Bundle\FelibBundle\Service\FelibService
        arguments: [ "%kernel.cache_dir%", "@request_stack", "@cache.provider.smart_felib", "%kernel.debug%" ]

    smart.felib.twig.extension:
        class: SmartCore\Bundle\FelibBundle\Twig\FelibExtension
        arguments: [ "@smart.felib" ]
        tags:
            - { name: twig.extension }
